import localFont from 'next/font/local'
import './globals.css'
import { Header } from './components/header'
import { Footer } from './components/footer'

const pretandard = localFont({
  src: './fonts/Pretendard-Regular.subset.woff2',
  weight: '400',
  style: 'normal',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${pretandard.className} flex flex-col justify-between min-h-screen m-0 gap-[20px]`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
