import localFont from 'next/font/local'
import './globals.css'

const pretandard = localFont({
  src: './fonts/Pretendard-Regular.subset.woff2',
  weight: '400',
  style: 'normal',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${pretandard.className} antialiased`}>{children}</body>
    </html>
  )
}
